### ISSUE TITLE
NullPointerExeption

### ISSUE THREAD

**Issue by teterev98** [akarazhev/metacfg4j#13]
Bug got NullPointerExeption, when get Config  without attributes.

     `Property property = new Property.Builder("newProperty","value").build();
        //creation of a Config without attributes
        Config config =  new Config.Builder("Config_Name", `Collections.singleton(property)).build();`
        metaConfig.update(Stream.of(config));

       //get method trows NullPointerExeption
       Stream<Config> configStream = metaConfig.get(Stream.of("Config_Name")); `

**Comment by akarazhev** [comment]
> Bug got NullPointerExeption, when get Config without attributes.
> 
> ```
>  `Property property = new Property.Builder("newProperty","value").build();
>     //creation of a Config without attributes
>     Config config =  new Config.Builder("Config_Name", `Collections.singleton(property)).build();`
>     metaConfig.update(Stream.of(config));
> 
>    //get method trows NullPointerExeption
>    Stream<Config> configStream = metaConfig.get(Stream.of("Config_Name")); `
> ```

Hi, thanks for the info. The fix will be in the next version: 1.8.
